### ISSUE TITLE
能加一个预测性别的吗？

### ISSUE THREAD

**Issue by daxu96** [VegetableWithChicken/OpenCV_DNN_FaceRecognize_For_UnrealEngine#3]
能加一个预测性别的吗？
<img width="301" alt="微信截图_20220906165946" src="https://user-images.githubusercontent.com/37661745/188593388-ba43f65b-992a-4c31-a204-4191182a3a54.png">

**Comment by VegetableWithChicken** [comment]
可以的，后面加进去通知你们哈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月6日(周二) 下午5:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [VegetableWithChicken/OpenCVForUnreal] 能加一个预测性别的吗？ (Issue #3)




 
能加一个预测性别的吗？

**Comment by daxu96** [comment]
> 可以的，后面加进去通知你们哈
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年9月6日(周二) 下午5:00 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [VegetableWithChicken/OpenCVForUnreal] 能加一个预测性别的吗？ (Issue #3) 能加一个预测性别的吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

 准确率咋样

**Comment by VegetableWithChicken** [comment]
一般都还可以的，放心，嘻嘻



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月6日(周二) 下午5:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [VegetableWithChicken/OpenCVForUnreal] 能加一个预测性别的吗？ (Issue #3)




  
可以的，后面加进去通知你们哈
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年9月6日(周二) 下午5:00 收件人: @.&gt;; 抄送: @.&gt;; 主题: [VegetableWithChicken/OpenCVForUnreal] 能加一个预测性别的吗？ (Issue #3) 能加一个预测性别的吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
准确率咋样

**Comment by VegetableWithChicken** [comment]
性别检测，替换加载模型即可，参考和下载文章如下(增加年龄和性别检测)
[文章查看](https://pythontechworld.com/article/detail/hlog1fPuCKNa)  
#### 模型下载链接
[Gender](https://www.dropbox.com/s/iyv483wz7ztr9gh/gender_net.caffemodel?dl=0)  
[Age](https://www.dropbox.com/s/xfb20y596869vbb/age_net.caffemodel?dl=0)
